config/routes.rb
Rails.application.routes.draw do
  get '/pets', to: 'pets#index'
  get '/pets/new', to: 'pets#new'
  get '/pets/:id', to: 'pets#show', as: :pet
  post '/pets', to: 'pets#create'
  delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(Dog Cat Rabbit Turtle Fish Elephant)

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.order(found_on: :desc)
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    pet = Pet.new(pet_params)
    pet.save

    redirect_to pet_path(pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/index.html.erb
<h1>Found Pets</h1>

<%= link_to 'I found a pet', pets_new_path, class: 'btn btn-primary' %>

<ul class="mt-3">
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %> - found <%= pet.found_days_ago %> days ago</li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<h1>Report a pet you found</h1>

<%= form_with model: @pet do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= f.label :species, class: 'form-label' %>
    <%= f.select :species, Pet::SPECIES, {}, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= f.label :found_on, class: 'form-label' %>
    <%= f.date_field :found_on, class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<ul>
  <li><%= @pet.species %></li>
  <li>Found <%= @pet.found_days_ago %> days ago</li>
</ul>

<%= link_to "<i class='fa-solid fa-trash-can'></i> Delete".html_safe,
            pet_path(@pet),
            class: 'text-decoration-none',
            data: { turbo_method: :delete, turbo_message: 'Are you sure?' } %>